ALTER TABLE "Site" ADD COLUMN "agentSyncIntervalHours" INTEGER NOT NULL DEFAULT 12;
ALTER TABLE "Site" ADD COLUMN "pageCheckIntervalHours" INTEGER NOT NULL DEFAULT 12;
ALTER TABLE "Site" ADD COLUMN "lastPageCheckAt" TIMESTAMP(3);
ALTER TABLE "Site" ADD COLUMN "nextPageCheckAt" TIMESTAMP(3);
